### ISSUE TITLE
An error occurred setting up the container

### ISSUE THREAD

**Issue by gmacario** [prenone/platformio-vscode-devcontainer#2]
Let me first congratulate for this awesome piece of software!

I have discovered a minor issue which is most likely due to a recent change in platformio-core repository organization.
Details below.

## Steps to reproduce

VSCode: View > Command Palette...

> Dev Containers: Clone Repository in Container Volume...

* Provide repository URL or pick a repository source: (GitHub)
* Repository name: `prenone/platformio-vscode-devcontainer`
* Branch name: master

After a few seconds the following error message is displayed:

![image](https://user-images.githubusercontent.com/75182/226198161-190dccca-777e-4c7a-93b6-14797ebd41c0.png)

> An error occurred setting up the container

**Comment by gmacario** [comment]
Here is the error log on VSCode terminal:

```text
 => ERROR [dev_container_auto_added_stage_label 3/4] RUN curl -fLo /etc/u  1.1s
------                                                                          
 > [dev_container_auto_added_stage_label 3/4] RUN curl -fLo /etc/udev/rules.d/99-platformio-udev.rules --create-dirs https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules:                      
#0 0.676   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                        
#0 0.676                                  Dload  Upload   Total   Spent    Left  Speed
  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#0 1.070 curl: (22) The requested URL returned error: 404
------
Dockerfile-with-features:27
--------------------
  25 |         && rm -rf /var/lib/apt/lists/*
  26 |     
  27 | >>> RUN curl -fLo /etc/udev/rules.d/99-platformio-udev.rules --create-dirs https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules
  28 |     
  29 |     USER $USERNAME
--------------------
error: failed to solve: process "/bin/sh -c curl -fLo /etc/udev/rules.d/99-platformio-udev.rules --create-dirs https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules" did not complete successfully: exit code: 22
[20891 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.31.0-1679249442609/Dockerfile-with-features -t vsc-platformio-vscode-devcontainer-6838e027795a2c14a12d92b16591059b --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /workspaces/platformio-vscode-devcontainer/.devcontainer
[20892 ms]     at hie (/root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1931:1698)
[20892 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[20892 ms]     at async FF (/root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1930:3910)
[20893 ms]     at async S7 (/root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1930:2839)
[20893 ms]     at async xie (/root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:2625)
[20893 ms]     at async Wf (/root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:3750)
[20893 ms]     at async noe (/root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17325)
[20893 ms]     at async roe (/root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17066)
[20921 ms] Exit code 1
[20921 ms] Start: Run in Host: docker rm -f d84fd56449a40fae144858a985b8641a7c89cef7520c9c41f1b8af3d162608d5
[20929 ms] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-0a926d00-78fd-431d-9cd2-31912a0957fb1679249418281 --workspace-folder /workspaces/platformio-vscode-devcontainer --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/prenone/platformio-vscode-devcontainer.git --id-label vsch.local.repository.volume=platformio-vscode-devcontainer-7f82d9ad54507a81a3fe4d10f7ca6dc3 --id-label vsch.local.repository.folder=platformio-vscode-devcontainer --id-label devcontainer.config_file=/workspaces/platformio-vscode-devcontainer/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/platformio-vscode-devcontainer/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-afad0815-c597-4c37-b728-a39fd6433c9b.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=platformio-vscode-devcontainer-7f82d9ad54507a81a3fe4d10f7ca6dc3,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[20929 ms] Exit code 1
[21287 ms] Container server terminated (code: 137, signal: null).
```

**Comment by gmacario** [comment]
Please see #1 for a possible fix

**Comment by prenone** [comment]
Thank you for reporting and fixing this. It makes me very happy to know that this code I wrote some years ago is still useful to someone. I guess its the beauty of Open Source

I approved https://github.com/prenone/platformio-vscode-devcontainer/pull/1 and I should really set up some automated tests...
